# Generated by Django 4.2.4 on 2023-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_question_alter_rightanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_answers',
            field=models.ManyToManyField(to='api.wronganswer'),
        ),
    ]
