# Generated by Django 4.2.4 on 2023-09-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_stage_levels_stage_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficult',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='difficult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.difficult'),
            preserve_default=False,
        ),
    ]
