# Generated by Django 4.2.4 on 2023-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_difficult_question_question_difficult'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
